# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAJ0-SvhzhHoJxIqPVwbaz-8fJtK9VOx
"""

notas = [7.5, 8.0, 6.5, 9.0, 5.5, 7.0, 8.5]

# calcular a média "na mão"
soma = 0
for n in notas:
    soma += n
media = soma / len(notas)
print(media)

import numpy as np

notas_np = np.array(notas)

print(notas_np.mean())     # média, sem loop manual
print(notas_np.std())      # desvio padrão, de graça
print(notas_np.shape)      # forma do array: (7,) = 7 elementos, 1 dimensão
print(notas_np.dtype)      # tipo dos dados: float64

notas_ajustadas = notas_np + 1
print(notas_ajustadas)

import numpy as np
import time

n = 10_000_000  # 10 milhões de elementos
lista_python = list(range(n))
array_numpy = np.arange(n)
print(lista_python[:20])
print(array_numpy[:20])

inicio = time.time()

resultado_python = [x * 2 for x in lista_python]

fim = time.time()
print(f"Python puro: {fim - inicio:.4f} segundos")

inicio = time.time()

resultado_numpy = array_numpy * 2

fim = time.time()
print(f"NumPy: {fim - inicio:.4f} segundos")

import matplotlib.pyplot as plt

tamanhos = [10_000, 100_000, 1_000_000, 5_000_000, 10_000_000]
tempos_python = []
tempos_numpy = []

for n in tamanhos:
    lista = list(range(n))
    arr = np.arange(n)

    inicio = time.time()
    _ = [x * 2 for x in lista]
    tempos_python.append(time.time() - inicio)

    inicio = time.time()
    _ = arr * 2
    tempos_numpy.append(time.time() - inicio)

plt.plot(tamanhos, tempos_python, label="Python puro", marker="o")
plt.plot(tamanhos, tempos_numpy, label="NumPy", marker="o")
plt.xlabel("Quantidade de elementos")
plt.ylabel("Tempo (segundos)")
plt.title("Python puro vs NumPy")
plt.legend()
plt.show()

